issuers:
  BC-REG:
    name: BC Corporate Registry
    abbreviation: BCReg
    url: "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/\
      ministries-organizations/ministries/citizens-services/bc-registries-online-services"
    email: bcreg.test.issuer@example.ca
    url: $APPLICATION_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
    wallet:
      seed: $WALLET_SEED_BCREG

    credential_types:
      - description: Incorporation
        schema: incorporation.bc_registries
        issuer_url: $APPLICATION_URL_INCORP
        topic:
          topic_type: legal-entity
          topic_source_id: legal_entity_id
        mapping:
          - model: name
            fields:
              text:
                input: legal_name
                from: claim
              type:
                input: legal_name
                from: value
          - model: address
            fields:
              addressee:
                input: addressee
                from: claim
              civic_address:
                input: address_line_1
                from: claim
              city:
                input: city
                from: claim
              province:
                input: province
                from: claim
              postal_code:
                input: postal_code
                from: claim
              country:
                input: country
                from: claim
              type:
                input: operating
                from: value

      - description: Doing Business As
        schema: doing_business_as.bc_registries
        issuer_url: $APPLICATION_URL_DBA
        topic:
          topic_type: legal-entity
          topic_source_id: legal_entity_id


verifiers:
  BC-TOB:
    name: BC OrgBook
    wallet:
      seed: "tob-verifier-wallet-000000000001"
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL


proof_requests:
  registration:
    version: "1.0.0"
    schemas:
      - key:
          # did: DtjQTjwNq7ZyStCE7zwL4r
          name: incorporation.bc_registries
          version: "1.0.31"
        attributes:
          - legal_entity_id
          - corp_num
          - legal_name
          - org_type
          - addressee
          - address_line_1
          - address_line_2
          - city
          - province
          - postal_code
          - country
          - effective_date
          - end_date
